import { execFile } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { copyFile, cp, mkdir, readdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { promisify } from 'node:util'

import { env } from './env.js'
import { mintApiKey } from './jwt.js'
import {
  createProjectRecord,
  deleteProjectRecord,
  generateRef,
  getProject,
  listProjects,
  type ProjectRecord,
  type ProjectSecrets,
  updateProjectStatus,
} from './projects-store.js'

const execFileAsync = promisify(execFile)

const COMPOSE_TIMEOUT_MS = 15 * 60 * 1000

export function projectsConfigured(): boolean {
  return Boolean(env.projectsDir && env.projectsHostDir)
}

function projectDir(ref: string): string {
  return path.join(env.projectsDir, ref)
}

function hostDir(ref: string): string {
  return path.posix.join(env.projectsHostDir, ref)
}

function composeProjectName(ref: string): string {
  return `sbproj-${ref}`
}

export function containerName(ref: string, service: string): string {
  return `sbproj-${ref}-${service}`
}

async function compose(ref: string, args: string[]): Promise<void> {
  await execFileAsync(
    'docker',
    [
      'compose',
      '-p',
      composeProjectName(ref),
      '--project-directory',
      projectDir(ref),
      ...args,
    ],
    { timeout: COMPOSE_TIMEOUT_MS, env: process.env }
  )
}

function composeFile(ref: string): string {
  const dir = hostDir(ref)
  const name = (service: string) => containerName(ref, service)
  // All services join the main stack's network so the gateway proxy
  // (management-api) and pg-meta can reach them by container name.
  return `# Generated by management-api. Do not edit: recreated on provisioning.
name: ${composeProjectName(ref)}

networks:
  default:
    external: true
    name: ${env.mainNetworkName}

volumes:
  # Named volume so the image's bundled config files under
  # /etc/postgresql-custom are copied in on first use.
  db-config:

services:
  db:
    container_name: ${name('db')}
    image: ${env.projectImages.postgres}
    restart: unless-stopped
    volumes:
      - ${dir}/db-init/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql:Z
      - ${dir}/db-init/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
      - ${dir}/db-init/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
      - ${dir}/db-init/jwt.sql:/docker-entrypoint-initdb.d/init-scripts/99-jwt.sql:Z
      - ${dir}/db-init/_supabase.sql:/docker-entrypoint-initdb.d/migrations/97-_supabase.sql:Z
      - ${dir}/db-init/logs.sql:/docker-entrypoint-initdb.d/migrations/99-logs.sql:Z
      - ${dir}/db-init/pooler.sql:/docker-entrypoint-initdb.d/migrations/99-pooler.sql:Z
      - ${dir}/db-data:/var/lib/postgresql/data:Z
      - db-config:/etc/postgresql-custom
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: 5432
      POSTGRES_PORT: 5432
      PGPASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      PGDATABASE: postgres
      POSTGRES_DB: postgres
      JWT_SECRET: \${JWT_SECRET}
      JWT_EXP: 3600
    command:
      [
        "postgres",
        "-c",
        "config_file=/etc/postgresql/postgresql.conf",
        "-c",
        "log_min_messages=fatal"
      ]

  rest:
    container_name: ${name('rest')}
    image: ${env.projectImages.postgrest}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://authenticator:\${POSTGRES_PASSWORD}@${name('db')}:5432/postgres
      PGRST_DB_SCHEMAS: public,graphql_public,storage
      PGRST_DB_EXTRA_SEARCH_PATH: public
      PGRST_DB_MAX_ROWS: 1000
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: \${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_APP_SETTINGS_JWT_SECRET: \${JWT_SECRET}
      PGRST_APP_SETTINGS_JWT_EXP: 3600
    command: ["postgrest"]

  auth:
    container_name: ${name('auth')}
    image: ${env.projectImages.gotrue}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: \${API_EXTERNAL_URL}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:\${POSTGRES_PASSWORD}@${name('db')}:5432/postgres
      GOTRUE_SITE_URL: \${SITE_URL}
      GOTRUE_URI_ALLOW_LIST: ""
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_SECRET: \${JWT_SECRET}
      GOTRUE_JWT_ISSUER: \${API_EXTERNAL_URL}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_EXTERNAL_PHONE_ENABLED: "false"
      GOTRUE_SMS_AUTOCONFIRM: "false"

  storage:
    container_name: ${name('storage')}
    image: ${env.projectImages.storage}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      rest:
        condition: service_started
    environment:
      ANON_KEY: \${ANON_KEY}
      SERVICE_KEY: \${SERVICE_ROLE_KEY}
      POSTGREST_URL: http://${name('rest')}:3000
      AUTH_JWT_SECRET: \${JWT_SECRET}
      DATABASE_URL: postgres://supabase_storage_admin:\${POSTGRES_PASSWORD}@${name('db')}:5432/postgres
      STORAGE_PUBLIC_URL: \${STORAGE_PUBLIC_URL}
      REQUEST_ALLOW_X_FORWARDED_PATH: "true"
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      GLOBAL_S3_BUCKET: stub
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: \${REF}
      REGION: local
      ENABLE_IMAGE_TRANSFORMATION: "false"
    volumes:
      - ${dir}/storage:/var/lib/storage:z

  functions:
    container_name: ${name('functions')}
    image: ${env.projectImages.edgeRuntime}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${dir}/functions:/home/deno/functions:z
    environment:
      SUPABASE_URL: \${SUPABASE_INTERNAL_URL}
      SUPABASE_PUBLIC_URL: \${STORAGE_PUBLIC_URL}
      SUPABASE_ANON_KEY: \${ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: \${SERVICE_ROLE_KEY}
      SUPABASE_DB_URL: postgresql://postgres:\${POSTGRES_PASSWORD}@${name('db')}:5432/postgres
      JWT_SECRET: \${JWT_SECRET}
      VERIFY_JWT: "true"
    command:
      [
        "start",
        "--main-service",
        "/home/deno/functions/main"
      ]
`
}

function envFile(ref: string, secrets: ProjectSecrets): string {
  const publicBase = `${env.publicUrl.replace(/\/$/, '')}/proj/${ref}`
  return [
    `REF=${ref}`,
    `POSTGRES_PASSWORD=${secrets.postgres_password}`,
    `JWT_SECRET=${secrets.jwt_secret}`,
    `ANON_KEY=${secrets.anon_key}`,
    `SERVICE_ROLE_KEY=${secrets.service_role_key}`,
    `SITE_URL=${env.publicUrl}`,
    `API_EXTERNAL_URL=${publicBase}/auth/v1`,
    `STORAGE_PUBLIC_URL=${publicBase}`,
    `SUPABASE_INTERNAL_URL=http://management-api:8085/proj/${ref}`,
    '',
  ].join('\n')
}

const DB_INIT_FILES = [
  'realtime.sql',
  'webhooks.sql',
  'roles.sql',
  'jwt.sql',
  '_supabase.sql',
  'logs.sql',
  'pooler.sql',
]

async function writeProjectFiles(ref: string, secrets: ProjectSecrets): Promise<void> {
  const dir = projectDir(ref)
  await mkdir(path.join(dir, 'db-init'), { recursive: true })
  await mkdir(path.join(dir, 'db-data'), { recursive: true })
  await mkdir(path.join(dir, 'storage'), { recursive: true })
  await mkdir(path.join(dir, 'functions'), { recursive: true })

  for (const file of DB_INIT_FILES) {
    await copyFile(path.join(env.dbInitDir, file), path.join(dir, 'db-init', file))
  }

  // The edge runtime needs the `main` dispatcher; reuse the stack's one.
  const mainDispatcher = path.join(env.functionsDir, 'main')
  await cp(mainDispatcher, path.join(dir, 'functions', 'main'), { recursive: true })

  await writeFile(path.join(dir, '.env'), envFile(ref, secrets), { mode: 0o600 })
  await writeFile(path.join(dir, 'docker-compose.yml'), composeFile(ref))
}

export function generateProjectSecrets(): ProjectSecrets {
  const jwtSecret = randomBytes(32).toString('base64url')
  return {
    postgres_password: randomBytes(24).toString('hex'),
    jwt_secret: jwtSecret,
    anon_key: mintApiKey('anon', jwtSecret),
    service_role_key: mintApiKey('service_role', jwtSecret),
  }
}

/**
 * Creates the project record and provisions the stack in the background.
 * Returns immediately with the COMING_UP record; poll status afterwards.
 */
export async function provisionProject(input: {
  name: string
  organizationId: number
}): Promise<ProjectRecord> {
  const ref = generateRef()
  const secrets = generateProjectSecrets()
  const record = await createProjectRecord({
    ref,
    name: input.name,
    organizationId: input.organizationId,
    kind: 'compose',
    secrets,
    status: 'COMING_UP',
  })

  void (async () => {
    try {
      await writeProjectFiles(ref, secrets)
      await compose(ref, ['--env-file', path.join(projectDir(ref), '.env'), 'up', '-d'])
      await updateProjectStatus(ref, 'ACTIVE_HEALTHY')
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      console.error(`provisioning ${ref} failed:`, message)
      await updateProjectStatus(ref, 'INIT_FAILED', message.slice(0, 2000)).catch(() => {})
    }
  })()

  return record
}

/** Tears the stack down (containers + data) and removes the record. */
export async function deprovisionProject(ref: string): Promise<void> {
  const project = await getProject(ref)
  if (!project) return
  await updateProjectStatus(ref, 'GOING_DOWN')
  try {
    if (project.kind === 'compose') {
      await compose(ref, ['down', '-v', '--remove-orphans']).catch((err) => {
        console.error(`compose down for ${ref} failed:`, err)
      })
      await rm(projectDir(ref), { recursive: true, force: true })
    }
  } finally {
    await deleteProjectRecord(ref)
  }
}

/** Restarts the stack of an existing compose project (after host reboot etc). */
export async function resumeProjects(): Promise<void> {
  if (!projectsConfigured()) return
  const projects = await listProjects()
  const refs = new Set((await readdir(env.projectsDir).catch(() => [])) as string[])
  for (const project of projects) {
    if (project.kind !== 'compose' || !refs.has(project.ref)) continue
    try {
      await compose(project.ref, [
        '--env-file',
        path.join(projectDir(project.ref), '.env'),
        'up',
        '-d',
      ])
    } catch (err) {
      console.error(`resuming ${project.ref} failed:`, err)
    }
  }
}
